version: '2'
engines:
  eslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
        - javascript
checks:
  method-complexity:
    enabled: false
  method-lines:
    enabled: false
ratings:
  paths:
    - index.js
exclude_patterns:
  - 'examples/'
  - 'test/'
